[config]
schemaVersion = "0.0.1"

[package]
namespace = "XuXiaolan"
name = "YandereCuteamena"
description = "Adds in a new... enemy?"
websiteUrl = "https://github.com/TeamXiaolan/YandereCuteamena"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
XuXiaolan-CodeRebirthLib = "0.0.1"

[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "../Packages"

[[build.copy]]
source = "../YandereCuteamena/bin/Release/netstandard2.1/com.github.xuuxiaolan.yanderecuteamena.dll"
target = "BepInEx/plugins/YandereCuteamena/"

[[build.copy]]
source = "../Assetbundles"
target = "BepInEx/plugins/YandereCuteamena/Assets"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = [ "lethal-company", ]
[publish.categories]
lethal-company = [ "mods", "tools", "libraries", "clientside", "serverside" ]